"""Run once to seed 25 real Indian government schemes."""
from app.db.database import SessionLocal
from app.models.models import GovernmentScheme

SCHEMES = [
    {
        "name": "PM Kisan Samman Nidhi",
        "ministry": "Ministry of Agriculture",
        "category": "agriculture",
        "description": "Income support of ₹6,000/year to small and marginal farmers.",
        "eligibility": "Small and marginal farmers with cultivable land up to 2 hectares. Must be an Indian citizen.",
        "benefits": "₹6,000 per year in three equal instalments of ₹2,000 directly to bank account.",
        "how_to_apply": "Apply at local Common Service Centre (CSC) or PM-KISAN portal.",
        "documents_required": ["Aadhaar card", "Land ownership documents", "Bank passbook"],
        "official_url": "https://pmkisan.gov.in",
    },
    {
        "name": "Ayushman Bharat PM-JAY",
        "ministry": "Ministry of Health and Family Welfare",
        "category": "health",
        "description": "Health insurance cover of ₹5 lakh per family per year for secondary and tertiary hospitalisation.",
        "eligibility": "Families listed in SECC 2011 database. Covers poor and vulnerable population.",
        "benefits": "Up to ₹5 lakh per year health coverage for hospitalisation across empanelled hospitals.",
        "how_to_apply": "Check eligibility on pmjay.gov.in. Get Ayushman card from nearest CSC or hospital.",
        "documents_required": ["Aadhaar card", "Ration card", "SECC database enrollment"],
        "official_url": "https://pmjay.gov.in",
    },
    {
        "name": "PM Awas Yojana (Urban)",
        "ministry": "Ministry of Housing and Urban Affairs",
        "category": "housing",
        "description": "Housing for All urban mission providing interest subsidy on home loans.",
        "eligibility": "Economically Weaker Section (EWS, income < ₹3L), Low Income Group (LIG, ₹3-6L), Middle Income Group (MIG, ₹6-18L). First-time home buyers.",
        "benefits": "Interest subsidy of 3-6.5% on home loans. EWS gets up to ₹2.67 lakh subsidy.",
        "how_to_apply": "Apply through scheduled commercial banks, housing finance companies, or PMAY portal.",
        "documents_required": ["Aadhaar card", "Income certificate", "Property documents", "Bank statements"],
        "official_url": "https://pmaymis.gov.in",
    },
    {
        "name": "PM Awas Yojana (Gramin)",
        "ministry": "Ministry of Rural Development",
        "category": "housing",
        "description": "Provides financial assistance to rural BPL families for construction of pucca houses.",
        "eligibility": "Rural households listed in SECC 2011. SC/ST, freed bonded labourers, minorities, disabled persons get priority.",
        "benefits": "₹1.2 lakh in plains, ₹1.3 lakh in hilly/NE states. Additional ₹12,000 for toilet under SBM.",
        "how_to_apply": "Apply at Gram Panchayat or Block Development Office.",
        "documents_required": ["Aadhaar card", "BPL card", "Bank account details", "Land ownership proof"],
        "official_url": "https://pmayg.nic.in",
    },
    {
        "name": "Pradhan Mantri Mudra Yojana (PMMY)",
        "ministry": "Ministry of Finance",
        "category": "entrepreneurship",
        "description": "Loans up to ₹10 lakh for non-farm micro/small enterprises.",
        "eligibility": "Any Indian citizen with a business plan for non-farm income generating activities. No collateral required.",
        "benefits": "Shishu: up to ₹50,000 | Kishore: ₹50,001-5L | Tarun: ₹5L-10L. Low interest rates.",
        "how_to_apply": "Apply at any public/private bank, microfinance institution, or mudra.org.in.",
        "documents_required": ["Aadhaar card", "PAN card", "Business plan", "Bank statements", "Address proof"],
        "official_url": "https://www.mudra.org.in",
    },
    {
        "name": "PM Scholarship Scheme (PMSS)",
        "ministry": "Ministry of Defence",
        "category": "education",
        "description": "Scholarships for children of ex-servicemen, ex-coast guard, and police personnel killed in action.",
        "eligibility": "Dependent wards of ex-servicemen/coast guard/RPF/RPSF personnel. Studying professional degree courses. Minimum 60% in Class 12.",
        "benefits": "₹2,500/month for boys, ₹3,000/month for girls studying professional courses.",
        "how_to_apply": "Apply online at ksb.gov.in within the notified dates.",
        "documents_required": ["Discharge book/PPO of ex-serviceman", "Class 12 marksheet", "Admission proof", "Bank account details"],
        "official_url": "https://ksb.gov.in",
    },
    {
        "name": "National Scholarship Portal (NSP) - Post Matric",
        "ministry": "Ministry of Social Justice",
        "category": "education",
        "description": "Post-matric scholarships for SC/ST/OBC/Minority students.",
        "eligibility": "SC/ST/OBC/Minority students studying Class 11 onwards. Family income limits vary by category (₹2-2.5L/year).",
        "benefits": "Maintenance allowance + tuition fees reimbursement. Amount varies by course and category.",
        "how_to_apply": "Apply at scholarships.gov.in before the deadline each academic year.",
        "documents_required": ["Caste/community certificate", "Income certificate", "Previous year marksheet", "Bank account", "Aadhaar"],
        "official_url": "https://scholarships.gov.in",
    },
    {
        "name": "Sukanya Samriddhi Yojana",
        "ministry": "Ministry of Finance",
        "category": "women_children",
        "description": "Small deposit savings scheme for girl child education and marriage expenses.",
        "eligibility": "Parents/guardians of girl child below 10 years of age. Only 2 girls per family (3 if twins).",
        "benefits": "8.2% interest rate (tax-free). Minimum ₹250/year, maximum ₹1.5L/year. Tax exemption under Section 80C.",
        "how_to_apply": "Open account at post office or authorised banks with a minimum deposit of ₹250.",
        "documents_required": ["Girl child's birth certificate", "Parent's Aadhaar & PAN", "Address proof"],
        "official_url": "https://www.indiapost.gov.in",
    },
    {
        "name": "Pradhan Mantri Jeevan Jyoti Bima Yojana (PMJJBY)",
        "ministry": "Ministry of Finance",
        "category": "insurance",
        "description": "Low-cost life insurance scheme providing ₹2 lakh death coverage.",
        "eligibility": "Indians aged 18-50 with a savings bank account. Auto-debit enabled.",
        "benefits": "₹2 lakh life cover for death due to any reason. Premium ₹436/year.",
        "how_to_apply": "Enrol through your bank branch, online banking, or Common Service Centre.",
        "documents_required": ["Bank account details", "Aadhaar card", "Consent-cum-declaration form"],
        "official_url": "https://financialservices.gov.in",
    },
    {
        "name": "Pradhan Mantri Suraksha Bima Yojana (PMSBY)",
        "ministry": "Ministry of Finance",
        "category": "insurance",
        "description": "Accident insurance scheme with ₹2 lakh accidental death/disability cover.",
        "eligibility": "Indians aged 18-70 with a bank account. Auto-debit enabled.",
        "benefits": "₹2 lakh for accidental death/total disability, ₹1 lakh for partial disability. Only ₹20/year premium.",
        "how_to_apply": "Enrol at your bank branch, via net banking, or CSC.",
        "documents_required": ["Bank account details", "Aadhaar card", "Consent form"],
        "official_url": "https://financialservices.gov.in",
    },
    {
        "name": "Atal Pension Yojana (APY)",
        "ministry": "Ministry of Finance",
        "category": "pension",
        "description": "Pension scheme for unorganised sector workers with guaranteed minimum pension.",
        "eligibility": "Indian citizens aged 18-40, not in any statutory social security scheme, with a savings bank account.",
        "benefits": "Guaranteed monthly pension of ₹1,000-5,000 after age 60. Government co-contributes 50% for eligible subscribers.",
        "how_to_apply": "Apply at your bank branch or post office. Fill APY subscriber registration form.",
        "documents_required": ["Bank account", "Aadhaar card", "Mobile number"],
        "official_url": "https://npscra.nsdl.co.in",
    },
    {
        "name": "PM Garib Kalyan Anna Yojana",
        "ministry": "Ministry of Consumer Affairs, Food & Public Distribution",
        "category": "food",
        "description": "Free food grain provision to poor families.",
        "eligibility": "National Food Security Act (NFSA) beneficiaries — priority households and Antyodaya Anna Yojana families.",
        "benefits": "5 kg free wheat/rice per person per month under NFSA.",
        "how_to_apply": "Covered automatically if you have a ration card. Contact local PDS dealer.",
        "documents_required": ["Ration card", "Aadhaar card (for eKYC at PDS shop)"],
        "official_url": "https://dfpd.gov.in",
    },
    {
        "name": "Pradhan Mantri Kaushal Vikas Yojana (PMKVY)",
        "ministry": "Ministry of Skill Development",
        "category": "skill_training",
        "description": "Free skill certification training to youth for employment and entrepreneurship.",
        "eligibility": "Indian youth — school/college dropouts, unemployed. No upper age limit for most courses.",
        "benefits": "Free industry-recognised training. ₹8,000 reward on passing assessment. Placement assistance.",
        "how_to_apply": "Find a training partner centre at pmkvyofficial.org or call toll-free 1800-123-9626.",
        "documents_required": ["Aadhaar card", "Bank account", "Educational certificates"],
        "official_url": "https://pmkvyofficial.org",
    },
    {
        "name": "Deen Dayal Antyodaya Yojana – NRLM (DAY-NRLM)",
        "ministry": "Ministry of Rural Development",
        "category": "women_livelihood",
        "description": "Mobilising rural poor women into Self Help Groups (SHGs) with credit access and livelihood support.",
        "eligibility": "Rural poor women, priority to SC/ST, minorities, disabled, and NFSA beneficiaries.",
        "benefits": "SHG formation, ₹10,000-15,000 revolving fund, bank linkage, skill training, and market linkage.",
        "how_to_apply": "Contact Block Development Office or local SHG federation.",
        "documents_required": ["Aadhaar card", "Bank account", "BPL/income certificate"],
        "official_url": "https://aajeevika.gov.in",
    },
    {
        "name": "Stand Up India",
        "ministry": "Ministry of Finance",
        "category": "entrepreneurship",
        "description": "Loans to SC/ST and women entrepreneurs to set up greenfield enterprises.",
        "eligibility": "SC/ST individuals or women above 18 years, setting up a new enterprise in manufacturing/services/trading.",
        "benefits": "Composite loan of ₹10 lakh to ₹1 crore. 7 year repayment. 18 months moratorium.",
        "how_to_apply": "Apply at any scheduled commercial bank branch or at standupmitra.in.",
        "documents_required": ["Aadhaar", "PAN", "Project report", "Caste certificate (if SC/ST)", "Bank statements"],
        "official_url": "https://www.standupmitra.in",
    },
    {
        "name": "Beti Bachao Beti Padhao",
        "ministry": "Ministry of Women and Child Development",
        "category": "women_children",
        "description": "Scheme to address declining child sex ratio and promote education of girl children.",
        "eligibility": "Girl child and their families in selected districts across India.",
        "benefits": "Conditional cash transfers, free education for girls, community awareness programs.",
        "how_to_apply": "Enrol at Anganwadi centre or local government school.",
        "documents_required": ["Girl child's birth certificate", "Parent's Aadhaar", "Address proof"],
        "official_url": "https://wcd.nic.in",
    },
    {
        "name": "PM Employment Generation Programme (PMEGP)",
        "ministry": "Ministry of MSME",
        "category": "entrepreneurship",
        "description": "Credit-linked subsidy for setting up micro-enterprises in non-farm sector.",
        "eligibility": "Any individual above 18 years. 8th pass for projects above ₹10L. Self-help groups, institutions also eligible.",
        "benefits": "15-35% subsidy on project cost up to ₹50L (manufacturing) / ₹20L (service). Bank provides remaining 55-60% as loan.",
        "how_to_apply": "Apply online at kviconline.gov.in or at nearest KVIC/KVIB/DIC office.",
        "documents_required": ["Aadhaar", "PAN", "Project report", "Educational certificates", "Caste certificate if applicable"],
        "official_url": "https://kviconline.gov.in",
    },
    {
        "name": "Pradhan Mantri Fasal Bima Yojana (PMFBY)",
        "ministry": "Ministry of Agriculture",
        "category": "agriculture",
        "description": "Crop insurance scheme protecting farmers against losses due to natural calamities.",
        "eligibility": "All farmers growing notified crops in notified areas. Loanee farmers compulsorily covered.",
        "benefits": "Crop loss compensation at insured sum. Maximum premium: 2% (Kharif), 1.5% (Rabi), 5% (commercial crops).",
        "how_to_apply": "Enrol through bank, CSC, or pmfby.gov.in before cutoff date for each season.",
        "documents_required": ["Land records", "Aadhaar", "Bank account", "Sowing certificate"],
        "official_url": "https://pmfby.gov.in",
    },
    {
        "name": "e-Shram Portal Registration",
        "ministry": "Ministry of Labour & Employment",
        "category": "labour",
        "description": "National database of unorganised workers with social security benefits.",
        "eligibility": "Unorganised sector workers aged 16-59 not covered under EPFO/ESIC/NPS.",
        "benefits": "e-Shram card, ₹2 lakh accident insurance under PMSBY, priority access to government schemes.",
        "how_to_apply": "Self-register at eshram.gov.in or at CSC.",
        "documents_required": ["Aadhaar card linked to mobile number", "Bank account details"],
        "official_url": "https://eshram.gov.in",
    },
    {
        "name": "PM Vishwakarma Yojana",
        "ministry": "Ministry of MSME",
        "category": "skill_training",
        "description": "Support for traditional artisans and craftspeople (Vishwakarma communities).",
        "eligibility": "Artisans in 18 traditional trades (carpenter, blacksmith, potter, weaver, etc.) from Vishwakarma communities.",
        "benefits": "₹15,000 tool kit, skill training stipend, collateral-free loans at 5% (₹1L first, ₹2L second tranche), market linkage.",
        "how_to_apply": "Apply at CSC or pmvishwakarma.gov.in.",
        "documents_required": ["Aadhaar", "Community certificate", "Bank account", "Trade proof"],
        "official_url": "https://pmvishwakarma.gov.in",
    },
    {
        "name": "Kisan Credit Card (KCC)",
        "ministry": "Ministry of Agriculture",
        "category": "agriculture",
        "description": "Revolving credit for farmers for crop cultivation, post-harvest expenses, and allied activities.",
        "eligibility": "Farmers, sharecroppers, oral lessees, self-help groups, and tenant farmers.",
        "benefits": "Credit limit of ₹3L+ at 7% interest (4% with prompt repayment). Covers inputs, equipment, household needs.",
        "how_to_apply": "Apply at any bank branch with land records or at CSC.",
        "documents_required": ["Land records/tenancy agreement", "Aadhaar", "PAN", "Passport photo"],
        "official_url": "https://www.nabard.org",
    },
    {
        "name": "MGNREGA (Mahatma Gandhi National Rural Employment Guarantee Act)",
        "ministry": "Ministry of Rural Development",
        "category": "employment",
        "description": "Guarantees 100 days of unskilled wage employment per year to rural households.",
        "eligibility": "Any adult member of a rural household willing to do unskilled manual work.",
        "benefits": "100 days guaranteed employment at state-notified minimum wage. Payment directly to bank account within 15 days.",
        "how_to_apply": "Register at local Gram Panchayat to get Job Card.",
        "documents_required": ["Aadhaar", "Bank account", "Passport size photo"],
        "official_url": "https://nrega.nic.in",
    },
    {
        "name": "National Social Assistance Programme (NSAP)",
        "ministry": "Ministry of Rural Development",
        "category": "pension",
        "description": "Social assistance to BPL elderly, widows, and disabled persons.",
        "eligibility": "BPL elderly (60+), widows (40+), disabled persons (18+) with 80%+ disability.",
        "benefits": "Monthly pension: ₹200-500 from centre + state top-up. Varies by state.",
        "how_to_apply": "Apply at Gram Panchayat or Block Office with BPL certificate.",
        "documents_required": ["BPL card", "Age proof", "Aadhaar", "Bank account"],
        "official_url": "https://nsap.nic.in",
    },
    {
        "name": "PM Ujjwala Yojana 2.0",
        "ministry": "Ministry of Petroleum",
        "category": "women_children",
        "description": "Free LPG connections to women from BPL families.",
        "eligibility": "Adult women from BPL households without existing LPG connection. SC/ST, PMAY, AAY, OBC beneficiaries prioritised.",
        "benefits": "Free LPG connection (deposit waived). First refill and stove (hotplate) free.",
        "how_to_apply": "Apply at nearest LPG distributor or at pmuy.gov.in.",
        "documents_required": ["Aadhaar card", "BPL/ration card", "Bank account"],
        "official_url": "https://pmuy.gov.in",
    },
    {
        "name": "Startup India Seed Fund Scheme",
        "ministry": "Ministry of Commerce and Industry",
        "category": "entrepreneurship",
        "description": "Financial assistance for proof of concept, prototype, product trials for early-stage startups.",
        "eligibility": "DPIIT-recognised startup, incorporated < 2 years ago, not received > ₹10L from any other govt scheme.",
        "benefits": "Up to ₹20L for proof of concept/prototyping, up to ₹50L for market entry/commercialisation.",
        "how_to_apply": "Apply at seedfund.startupindia.gov.in.",
        "documents_required": ["DPIIT recognition certificate", "Incorporation certificate", "PAN", "Bank details", "Pitch deck"],
        "official_url": "https://seedfund.startupindia.gov.in",
    },
]

def seed_schemes():
    db = SessionLocal()
    try:
        existing = db.query(GovernmentScheme).count()
        if existing > 0:
            print(f"Schemes already seeded ({existing} found). Skipping.")
            return

        for s in SCHEMES:
            scheme = GovernmentScheme(**s)
            db.add(scheme)
        db.commit()
        print(f"✅ Seeded {len(SCHEMES)} government schemes.")
    finally:
        db.close()

if __name__ == "__main__":
    seed_schemes()